default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: loco_ip_api_development

test:
  <<: *default
  database: loco_ip_api_test
