name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:9.5
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby for use with actions
        uses: actions/setup-ruby@v1.0.0
        env:
          RAILS_ENV: test
        with:
          version: 2.7.0

      - name: Cache Gems
        id: gem-cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Bundle Install and Create DB
        env:
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4
          bundle exec rails db:setup

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec
